// scripts/ingest-laws.ts
//
// One-off script to (re)ingest the Jordanian legal corpus into the
// "LegalCorpus" table, with embeddings generated by Gemini.
//
// Usage:
//   GEMINI_API_KEY=... DATABASE_URL=... tsx scripts/ingest-laws.ts
//
// Idempotent: upserts by `id` (stable slug from data/jordanian-corpus.ts).
// Run multiple times safely; existing rows are updated, embeddings regenerated.
//
// Free tier limits (Gemini embedding-001):
//   - 1500 requests/minute, 1500/day
//   - We batch sequentially with small delays to stay safely under RPM.

import { PrismaClient } from "@prisma/client";
import { CORPUS, type CorpusArticle } from "../data/jordanian-corpus";

const prisma = new PrismaClient();
const EMBED_MODEL = "gemini-embedding-001";
const EMBED_DIM = 768;
const SLEEP_MS = 250; // ~4 req/s = 240 RPM, well under 1500

// -------- Embedding --------

async function embed(text: string): Promise<number[] | null> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY not set");
  }
  const cleaned = text.replace(/\s+/g, " ").trim().slice(0, 8000);
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${EMBED_MODEL}:embedContent?key=${apiKey}`;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      const r = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: { parts: [{ text: cleaned }] },
          outputDimensionality: EMBED_DIM,
        }),
      });
      if (r.ok) {
        const j = (await r.json()) as { embedding?: { values?: number[] } };
        const v = j.embedding?.values;
        if (v && v.length === EMBED_DIM) return v;
        throw new Error(`Bad embedding dim: ${v?.length}`);
      }
      if (r.status === 429 || r.status === 503) {
        const wait = 1000 * attempt;
        console.warn(`  ⏳ ${r.status}, retrying in ${wait}ms…`);
        await new Promise((r) => setTimeout(r, wait));
        continue;
      }
      throw new Error(`HTTP ${r.status}: ${(await r.text()).slice(0, 200)}`);
    } catch (e) {
      if (attempt === 3) throw e;
      await new Promise((r) => setTimeout(r, 500 * attempt));
    }
  }
  return null;
}

// -------- Upsert --------

async function upsertArticle(a: CorpusArticle, idx: number, total: number) {
  const embeddingText = `${a.lawName} ${a.articleNumber ?? ""} ${a.title}. ${a.content}`;
  const embedding = await embed(embeddingText);

  await prisma.legalCorpus.upsert({
    where: { id: a.id },
    update: {
      lawName: a.lawName,
      lawType: a.lawType,
      articleNumber: a.articleNumber,
      title: a.title,
      content: a.content,
      metadata: a.metadata ?? { source: "manual-curation" } as object,
    },
    create: {
      id: a.id,
      lawName: a.lawName,
      lawType: a.lawType,
      articleNumber: a.articleNumber,
      title: a.title,
      content: a.content,
      metadata: a.metadata ?? { source: "manual-curation" } as object,
    },
  });

  if (embedding && embedding.length === EMBED_DIM) {
    const vec = "[" + embedding.join(",") + "]";
    await prisma.$executeRawUnsafe(
      `UPDATE "LegalCorpus" SET embedding = $1::vector WHERE id = $2`,
      vec,
      a.id,
    );
    console.log(`  ✓ [${idx + 1}/${total}] ${a.lawName} ${a.articleNumber ?? ""} — ${a.title}`);
  } else {
    console.warn(`  ✗ [${idx + 1}/${total}] no embedding for ${a.id}`);
  }
}

// -------- Main --------

async function main() {
  const start = Date.now();
  console.log(`\nIngesting ${CORPUS.length} Jordanian legal articles…\n`);

  if (!process.env.GEMINI_API_KEY) {
    console.error("✗ GEMINI_API_KEY is not set. Cannot generate embeddings.");
    process.exit(1);
  }
  if (!process.env.DATABASE_URL && !process.env.DIRECT_URL) {
    console.error("✗ DATABASE_URL / DIRECT_URL is not set. Cannot connect to Postgres.");
    process.exit(1);
  }

  let okCount = 0;
  let failCount = 0;
  for (let i = 0; i < CORPUS.length; i++) {
    try {
      await upsertArticle(CORPUS[i], i, CORPUS.length);
      okCount++;
    } catch (e) {
      failCount++;
      console.error(`  ✗ [${i + 1}/${CORPUS.length}] ${CORPUS[i].id} failed:`, (e as Error).message?.slice(0, 200));
    }
    // Small delay between requests to respect RPM limit
    if (i < CORPUS.length - 1) await new Promise((r) => setTimeout(r, SLEEP_MS));
  }

  const elapsed = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`\nDone in ${elapsed}s — ${okCount} succeeded, ${failCount} failed.`);
  if (failCount > 0) process.exit(1);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
